/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as KeyboardRouteImport } from './routes/keyboard'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as NdebeRouteImport } from './routes/ndebe'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PractiseRouteImport } from './routes/practise'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TutorRouteImport } from './routes/tutor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyboardRoute = KeyboardRouteImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const NdebeRoute = NdebeRouteImport.update({
  id: '/ndebe',
  path: '/ndebe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PractiseRoute = PractiseRouteImport.update({
  id: '/practise',
  path: '/practise',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dictionary': typeof DictionaryRoute
  '/keyboard': typeof KeyboardRoute
  '/learn': typeof LearnRoute
  '/ndebe': typeof NdebeRoute
  '/platform': typeof PlatformRoute
  '/practise': typeof PractiseRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRoute
  '/teachers': typeof TeachersRoute
  '/tutor': typeof TutorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dictionary': typeof DictionaryRoute
  '/keyboard': typeof KeyboardRoute
  '/learn': typeof LearnRoute
  '/ndebe': typeof NdebeRoute
  '/platform': typeof PlatformRoute
  '/practise': typeof PractiseRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRoute
  '/teachers': typeof TeachersRoute
  '/tutor': typeof TutorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dictionary': typeof DictionaryRoute
  '/keyboard': typeof KeyboardRoute
  '/learn': typeof LearnRoute
  '/ndebe': typeof NdebeRoute
  '/platform': typeof PlatformRoute
  '/practise': typeof PractiseRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRoute
  '/teachers': typeof TeachersRoute
  '/tutor': typeof TutorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dictionary'
    | '/keyboard'
    | '/learn'
    | '/ndebe'
    | '/platform'
    | '/practise'
    | '/profile'
    | '/reset-password'
    | '/staff'
    | '/teachers'
    | '/tutor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dictionary'
    | '/keyboard'
    | '/learn'
    | '/ndebe'
    | '/platform'
    | '/practise'
    | '/profile'
    | '/reset-password'
    | '/staff'
    | '/teachers'
    | '/tutor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dictionary'
    | '/keyboard'
    | '/learn'
    | '/ndebe'
    | '/platform'
    | '/practise'
    | '/profile'
    | '/reset-password'
    | '/staff'
    | '/teachers'
    | '/tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DictionaryRoute: typeof DictionaryRoute
  KeyboardRoute: typeof KeyboardRoute
  LearnRoute: typeof LearnRoute
  NdebeRoute: typeof NdebeRoute
  PlatformRoute: typeof PlatformRoute
  PractiseRoute: typeof PractiseRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StaffRoute: typeof StaffRoute
  TeachersRoute: typeof TeachersRoute
  TutorRoute: typeof TutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyboard': {
      id: '/keyboard'
      path: '/keyboard'
      fullPath: '/keyboard'
      preLoaderRoute: typeof KeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ndebe': {
      id: '/ndebe'
      path: '/ndebe'
      fullPath: '/ndebe'
      preLoaderRoute: typeof NdebeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practise': {
      id: '/practise'
      path: '/practise'
      fullPath: '/practise'
      preLoaderRoute: typeof PractiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DictionaryRoute: DictionaryRoute,
  KeyboardRoute: KeyboardRoute,
  LearnRoute: LearnRoute,
  NdebeRoute: NdebeRoute,
  PlatformRoute: PlatformRoute,
  PractiseRoute: PractiseRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StaffRoute: StaffRoute,
  TeachersRoute: TeachersRoute,
  TutorRoute: TutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
